### ISSUE TITLE
Scripts for mBart and M2M fine-tuning

### ISSUE THREAD

**Issue by speedcell4** [Smu-Tan/ZS-NMT-Variations#2]
Hi, thanks for sharing the datasets and source code.

Could you please share your fine-tuning scripts with me? `mBart50`, `m2m100-419m`, `m2m100-1.2b`?

Thanks in ahead~

**Comment by Smu-Tan** [comment]
@speedcell4 Hi Yiran, I just uploaded the guidance scripts for fine-tuning mBart50. Below are some important points:

1. mBart50 does NOT support all 40 languages in our EC40, therefore we need to expand things for these unseen languages (See details [here](https://github.com/Smu-Tan/ZS-NMT-Variations/blob/main/train-eval-baseline-scripts/training_scripts/mbart50/3-train-EC40-mBart50.sh)). For example, if you have an unseen language xx, then expand:
a. vocabulary (to specify the language xx), this is done by adding xx to lang_dict.
b. embedding weights. this corresponds to the vocabulary, e.g.: the original encoder.embed_tokens.weight.shape = (250054, 1024) containing 50 languages, but now we have 1 unseen language xx, so we have to expand for it (randomly initialized). 

2. We did NOT fine-tune on m2m100 models, as we mentioned in the paper (page 4: "Additionally, we evaluated m2m-100 models directly in our evaluations without any fine-tuning."). Thus, you could take the released m2m100 models like 419m or 1.2b to test them directly.

Plus: we uploaded the pre-processed train, val, test sets (Fairseq bin format) for easy reproduction, see [here](https://github.com/Smu-Tan/ZS-NMT-Variations/tree/main?tab=readme-ov-file#download-and-use-ec40-directly-fairseq:~:text=Download%20and%20Use%20EC40%20directly%20(Fairseq)).



Please let me know if you have any other questions.

**Comment by speedcell4** [comment]
Thank you so much for such detailed replies! Really helpful~
