### ISSUE TITLE
Questions about the pre-processing details

### ISSUE THREAD

**Issue by speedcell4** [Smu-Tan/ZS-NMT-Variations#4]
Hello.

If I want to use the plain dataset that you provide in [Google drive](https://drive.google.com/drive/folders/1nZsDnj3mNKynk2D46frnLfmR9qTFzVM9), do I still need to run the preparation scripts in [this folder](https://github.com/Smu-Tan/ZS-NMT-Variations/tree/main/get-val-test-data/get_plain_scripts)?

Besides, I noticed you mentioned that "we filtered pairs whose length ratios are over 1.5" in the paper, so does that mean this filtering has already been accomplished in the plain dataset? for all train, dev, and test splits? I don't need to do this by myself?

And, do I need to do any other filtering? such as filtering out sentences that are longer than 128 or 256 after BPE encoding?

**Comment by Smu-Tan** [comment]
Hi @speedcell4 

1. > If I want to use the plain dataset that you provide in [Google drive](https://drive.google.com/drive/folders/1nZsDnj3mNKynk2D46frnLfmR9qTFzVM9), do I still need to run the preparation scripts in [this folder](https://github.com/Smu-Tan/ZS-NMT-Variations/tree/main/get-val-test-data/get_plain_scripts)?  

If you download plain [train_set](https://drive.google.com/drive/folders/1evcBALF8YfqCbtVg4rBB8C9vMbzydZiK?usp=drive_link), [val_set](https://drive.google.com/drive/folders/1iyNTvpX1Twc3hsn97n6U5RW_zTAEzfQ1?usp=drive_link), and [test_set ](https://drive.google.com/drive/folders/1s0BzSyOoEaHBeryzFVOADgoxaoM5W8ll?usp=drive_link)directly, there's no need to run the preparation scripts. The preparation code is only used if you download Ntrex and Flores from their repository, the version we provided has done these processes already.

2.  > Besides, I noticed you mentioned that "we filtered pairs whose length ratios are over 1.5" in the paper, so does that mean this filtering has already been accomplished in the plain dataset? for all train, dev, and test splits? I don't need to do this by myself?

The filtering has been done for plain train_set only, and it is a standard MT data processing step.

3. And, do I need to do any other filtering? such as filtering out sentences that are longer than 128 or 256 after BPE encoding?

We use this [bash_file](https://github.com/Smu-Tan/ZS-NMT-Variations/tree/main/train-eval-baseline-scripts#:~:text=3%20weeks%20ago-,Optional_build_fairseq_sharded_dataset.sh,-update%20scripts) to build sentencepiece vocabulary and this [train_bash](https://github.com/Smu-Tan/ZS-NMT-Variations/blob/main/train-eval-baseline-scripts/training_scripts/mTransformer/1-train-EC40-mT-big.sh) to train baseline models, you can refer them.

**Comment by speedcell4** [comment]
Thank you so much~
